### ISSUE TITLE
ECR support

### ISSUE THREAD

**Issue by zmarouf** [deislabs/oras#105]
Hello,

I tried using ORAS with ECR support and I get `Error: unexpected response: 404 Not Found`
I know the project is still in its infancy but I wanted to hack on it in AWS and I was wondering if anyone got it to work. Anything I can do to help test this? :)

**Comment by jdolitsky** [comment]
@zmarouf I don't think ECR supports arbitrary content types at this time. Maybe you can send feature request to their support?

Alternatively, you can run a custom registry on AWS EC2 node. container, etc:
```
docker run -it --rm -p 5000:5000 registry
```
All config options [here](https://docs.docker.com/registry/configuration/)

**Comment by jdolitsky** [comment]
@zmarouf I've just opened https://github.com/aws/containers-roadmap/issues/308

**Comment by zmarouf** [comment]
Awesome! Thank you so much for confirming this and opening a ticket chez AWS's appropriate repo.
I'll play with the custom registry for now! :)

**Comment by RichiCoder1** [comment]
This is now official supported in ECR, so all that's left is ECR auth right?
