### ISSUE TITLE
New ORAS Specification

### ISSUE THREAD

**Issue by jdolitsky** [deislabs/oras#106]
I suggest that:

- the admins of deislabs org create a new repo at deislabs/oras-spec
- a new **ORAS Specification** is created, based upon the content of [this PR](https://github.com/opencontainers/distribution-spec/pull/65)
- any tools using the ORAS CLI/Go module should adhere to this spec by default
- build and launch a simple informational webpage (e.g. oras-spec.org)

The ORAS Specification should be a superset of the [OCI Distribution Specification](https://github.com/opencontainers/distribution-spec).

The primary goal is so that tools wishing to leverage OCI for arbitrary artifact distribution have an opinionated framework for doing so.

The secondary goal is to continue to garner support and prove out the ORAS method of doing things, and potentially/eventually/hopefully making this a part of OCI proper.

A non-goal of the spec is to fragment the OCI ecosystem. It is not meant to divide, but to further enable and embolden orgs that wish to achieve multi-artifact support _today_. If you are reading this as a registry provider - your thoughts here are appreciated (even if it is that of indifference).

cc: @SteveLasker @sajayantony @glyn @jzelinskie @bacongobbler @lachie83

**Comment by SteveLasker** [comment]
Thanks @jdolitsky for pushing on this.
I'm hopeful we can get some traction with the OCI working group, as your non-goal is a real concern. Lets see if we can get some quorum in this weeks meeting. @jzelinskie, it would be helpful if you can attend the call and speak to your feedback on the pr: https://github.com/opencontainers/distribution-spec/pull/65/

**Comment by jdolitsky** [comment]
Hi, closing in favor of https://github.com/opencontainers/tob/issues/59!
