### ISSUE TITLE
Add new store that complies with OCI Image Layout Spec

### ISSUE THREAD

**Issue by jdolitsky** [deislabs/oras#107]
Add new `OCIStore` at pkg/content/oci.go that strictly follows the [OCI Image Layout Spec](https://github.com/opencontainers/image-spec/blob/master/image-layout.md). 

Example OCI Image storage layout on filesystem:
```
./index.json
./oci-layout
./blobs/sha256/3588d02542238316759cbf24502f4344ffcc8a60c803870022f335d1390c13b4
./blobs/sha256/4b0bc1c4050b03c95ef2a8e36e25feac42fd31283e8c30b3ee5df6b043155d3c
./blobs/sha256/7968321274dc6b6171697c33df7815310468e694ac5be0ec03ff053bb135e768
```

`oci-layout` looks like

```
{
    "imageLayoutVersion": "1.0.0"
}
```

example `index.json` looks like

```
{
  "schemaVersion": 2,
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.index.v1+json",
      "size": 7143,
      "digest": "sha256:0228f90e926ba6b96e4f39cf294b2586d38fbb5a1e385c05cd1ee40ea54fe7fd",
      "annotations": {
        "org.opencontainers.image.ref.name": "stable-release"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "size": 7143,
      "digest": "sha256:e692418e4cbaf90ca69d05a66403747baa33ee08806650b51fab815ad7fc331f",
      "platform": {
        "architecture": "ppc64le",
        "os": "linux"
      },
      "annotations": {
        "org.opencontainers.image.ref.name": "v1.0"
      }
    },
    {
      "mediaType": "application/xml",
      "size": 7143,
      "digest": "sha256:b3d63d132d21c3ff4c35a061adf23cf43da8ae054247e32faa95494d904a007e",
      "annotations": {
        "org.freedesktop.specifications.metainfo.version": "1.0",
        "org.freedesktop.specifications.metainfo.type": "AppStream"
      }
    }
  ],
  "annotations": {
    "com.example.index.revision": "r124356"
  }
}
```

The archive importer and exporter from containerd has a lot of good stuff:

https://github.com/containerd/containerd/blob/129942ca4d5764be1af04e03a30c841ddb452e11/images/archive/importer.go#L82

https://github.com/containerd/containerd/blob/b7f093eaa2785af9ca41ea27d0fd2a15a34603a2/images/archive/exporter.go#L323

cc @bacongobbler @shizhMSFT @sajayantony

**Comment by sajayantony** [comment]
So this is more about the the local file store or moving to use index?

**Comment by jdolitsky** [comment]
@sajayantony this is about local store. Obviously for the concepts introduced by the CLI, it is not as useful, but it is important for consumers or oras as a module.

`index.json`, i believe, can techincally just be a bunch of manifests and layers (do not need to add a `vnd.oci.image.index.v1+json` for example)

**Comment by bacongobbler** [comment]
It'd be great to get this in for the first beta release of Helm. I imagine this would be a backwards-incompatibility change for users running `helm chart save`. The filesystem layout would change, which would cause prior runs of `helm chart save` to not work with `helm push`.

**Comment by sajayantony** [comment]
Yes.. changing the file system will be hard and avoiding local store breakage would be good. /cc @shizhMSFT

**Comment by jdolitsky** [comment]
Just FYI - I've begun working on this in Helm dev-v3 fork without any ORAS changes: https://github.com/helm/helm/compare/dev-v3...jdolitsky:oci-image-spec?expand=1

It's still unclear to me the correct place to put these things cc @sajayantony @shizhMSFT
