### ISSUE TITLE
Support insecure registry

### ISSUE THREAD

**Issue by pytimer** [deislabs/oras#109]
## Oras version:
```sh
$ oras version
Version:        0.6.0
Go version:     go1.12.4
Git commit:     b285197778e05cd348abb8ff50faf0ef7e3554a2
Git tree state: clean
```

## What happened

Now i use `oras` to login the harbor registry, it failed. The error log:

```sh
$ oras login docker.hikcloud:30001
Username: admin
Password:
INFO[0005] Error logging in to v2 endpoint, trying next endpoint: Get https://docker.registry/v2/: x509: certificate has expired or is not yet valid
Error: Get https://docker.registry/v2/: x509: certificate has expired or is not yet valid
```

I use the docker client and config the `insecure-registries`, it login successed.

I see the oras code about login, i find the oras can't setting the `insecure-registries` parameter, so i hope the oras can add this flags when login the registry.

Is it my idea correct? If this idea ok, i can implement this feature.

**Comment by jdolitsky** [comment]
closed via #110 & #112
