### ISSUE TITLE
Move verbose logging into the library and out of cmd?

### ISSUE THREAD

**Issue by deitch** [deislabs/oras#140]
Would you consider moving the verbose logging defined in [pushStatusTrack()](https://github.com/deislabs/oras/blob/master/cmd/oras/push.go#L186-L196) and [pullStatusTrack()](https://github.com/deislabs/oras/blob/master/cmd/oras/pull.go#L117-L133) into `pkg/oras` and out of `cmd/oras`? The logging is highly image pull/push specific, and thus quiet useful to others using the oras library, not just the CLI.

I needed it, ended up duplicating almost the entire bit of code. 

What I did is pass an `io.Writer` to `push`/`pull` so rather than having the library write to stdout with `fmt.Println` (which may not be desired), it writes to the passed writer, if provided. It looks something like this:

```go
func pushStatusTrack(writer io.Writer) images.Handler {
        var printLock sync.Mutex
        return images.HandlerFunc(func(ctx context.Context, desc ocispec.Descriptor) ([]ocispec.Descriptor, error) {
                if name, ok := content.ResolveName(desc); ok {
                        printLock.Lock()
                        defer printLock.Unlock()
                        writer.Write([]byte(fmt.Sprintf("Uploading %s %s", desc.Digest.Encoded()[:12], name)))
                }
                return nil, nil
        })
}
```

And then you can pass the `io.Writer` and `verbose` option via `opts ...PushOpt`

I don't mind opening a PR for it. 

Thanks!

**Comment by sajayantony** [comment]
@jdolitsky would this help helm as well?

**Comment by jdolitsky** [comment]
Yes, i think itd be helpful

**Comment by SteveLasker** [comment]
@deitch, we'd welcome the PR to make logging easier for folks

**Comment by deitch** [comment]
Done, see #179
