### ISSUE TITLE
ORAS compliance with current OCI Artifacts proposal

### ISSUE THREAD

**Issue by Silvanoc** [deislabs/oras#150]
The proposal for OCI Artifacts specifies that **manifest configurations** should be of type  [`application/vnd.`[org|company]`.`[objectType]`.`[optionalSubType]`.config.`[version]`+json`](https://github.com/opencontainers/artifacts/blob/9b08de02a3c675baa9163b7b4c0b1140ea80c944/spec.md#defining-a-unique-artifact-type), but ORAS doesn't enforce neither the `config` (before the version) nor the `json` (after the version) literals.

I don't understand the rational behind those literals, but that's a different discussion... The point is that if ORAS is the reference implementation of the specification, but either the specification should specify those literals, or ORAS should enforce it.

The same applies to the **blobs/layers** [`application/vnd.`[org|company]`.`[layerType]`.`[layerSubType]`.layer.`[version]`.`[fileFormat]`+`[OPTIONAL compressionFormat]`](https://github.com/opencontainers/artifacts/blob/9b08de02a3c675baa9163b7b4c0b1140ea80c944/spec.md#defining-layer-types) WRT the `layer` literal (before the version).

**Comment by jdolitsky** [comment]
@SteveLasker - maybe you can comment.

If the proposal artifact spec states this about layers, then it is outdated, as we discussed these should be normal content types such as `text/plain`.

As for the manifest config - sure, you are right. Perhaps we enforce and add a flag to override and push anything. In any case this is still all very "in motion"

**Comment by Silvanoc** [comment]
Sorry, I forgot to update here, that I've already brought the same discussion to the Artifacts specification. See my comments [here](https://github.com/opencontainers/artifacts/pull/13) and the comments already provided by @SteveLasker

**Comment by SteveLasker** [comment]
I'll make some tweaks to the Artifacts spec PR, that will catch up with the conversations. I believe we said the config object can be any texttual type. But, it should express the type int he mediaType. If the config object uses json, `+json`. If the artifact uses yaml, `+yaml`. 
I also need to finish up the Iana.org registration, then incorporate that into the Artifacts spec as well. I'd suggest making a tracking issue under Oras to reflect the final state of artifacts, for how `manifest.config.mediaTypes` are uniquely defined.

**Comment by SteveLasker** [comment]
@Silvanoc, I believe this is now resolved with the latest updates. 
Please re-open if you feel we're missing something.
