### ISSUE TITLE
How to avoid warnings from containerd due to unkown types

### ISSUE THREAD

**Issue by Silvanoc** [deislabs/oras#151]
Not using any of the [media types supported by the OCI-image specification](https://github.com/opencontainers/image-spec/blob/master/manifest.md#image-manifest-property-descriptions) results in warnings from "[github.com/containerd/containerd/images/image.go](https://github.com/containerd/containerd/blob/v1.3.3/images/image.go)":

```
time="xyz" level=warning msg="encountered unknown type application/x.silvanoc.myapp.artifact.v1; children may not be fetched"
time="xyz" level=warning msg="reference for unknown type: application/x.silvanoc.myapp.artifact.v1" digest="sha256:xyz" mediatype=application/x.silvanoc.myapp.artifact.v1 size=xyz
```

Something similar happens if not providing any `config` or one of a different media type than [expected](https://github.com/opencontainers/image-spec/blob/master/manifest.md#image-manifest-property-descriptions):

```
time="xyz" level=warning msg="encountered unknown type application/vnd.unknown.config.v1+json; children may not be fetched"
time="xyz" level=warning msg="reference for unknown type: application/vnd.unknown.config.v1+json" digest="sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a" mediatype=application/vnd.unknown.config.v1+json size=2
```
Is there any way to avoid those warnings?

In my quick analysis I have the impression that the only option would be contributing a patch to containerd for the [Handler interface](https://github.com/containerd/containerd/blob/v1.3.3/images/handlers.go#L45) to support a flag like "do not check media type" or, even better, "check media type against following list". If that's the case, it might not be the effort worth...

**Comment by Silvanoc** [comment]
Using the Go API, not the CLI.

**Comment by jdolitsky** [comment]
@Silvanoc You can use something like:
```
import (
  orascontext "github.com/deislabs/oras/pkg/context"
)

oras.Pull(orascontext.Background(), ...
```

Here is how it is done in Helm: https://github.com/helm/helm/blob/master/internal/experimental/registry/client.go#L152

If debug enabled, we do not suppress output. See `ctx` helper method: https://github.com/helm/helm/blob/master/internal/experimental/registry/util.go#L59

**Comment by SteveLasker** [comment]
@Silvanoc, did @jdolitsky cover the issue? Can we close?

**Comment by Silvanoc** [comment]
I'm sorry, but I'm currently not assigned to work in this topic. Therefore I cannot test it in a while.

I think that my problem description was clear enough so that @jdolitsky (being one of the main contributors to the project) was able to give me the right answer. @SteveLasker feel free to close this ticket.
