### ISSUE TITLE
Oras Pull Manifest Using CLI 

### ISSUE THREAD

**Issue by sowu880** [deislabs/oras#196]
Since manifest stores meta data of image which is important to developers. 
Is that possible add a CLI tool for just pull manifest and just pull one blob by digest?

**Comment by shizhMSFT** [comment]
Pulling manifest and single blobs are not aimmed by ORAS CLI but possible with its golang package. Usually, those operations should be achieved by a generic registry client.

**Comment by shizhMSFT** [comment]
However, similar stuffs can be achieved by **oras pull with cache** #203.

Since the cache also caches the manifest, you can get the manifest and individual files in the cache.
```bash
digest=$(oras pull localhost:5000/hello:latest | tail -n1 | cut -d' ' -f2)
cat "${ORAS_CACHE}/blobs/$(echo -n $digest | tr ':' '/')" | jq .
```
