### ISSUE TITLE
Security Issue: Request for contact

### ISSUE THREAD

**Issue by pwntester** [deislabs/oras#201]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

Kind regards,
A

**Comment by SteveLasker** [comment]
This item is being actively tracked & fixed. We're also working on establishing a notification system for those consuming ORAS.
If you are a consumer of ORAS, please reach out while we get this process in place. Steve dot Lasker at microsoft dot com
