### ISSUE TITLE
Error in getting oras version 0.9.0

### ISSUE THREAD

**Issue by nishakm** [deislabs/oras#211]
I'm trying to import github/com/deislabs/oras/pkg/auth, but I get this error:

```
go: found github.com/deislabs/oras/pkg/auth/docker in github.com/deislabs/oras v0.9.0
go: github.com/deislabs/oras@v0.9.0 requires
        github.com/docker/distribution@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
I've tried running `go get` but cannot resolve this dependency.

**Comment by jdolitsky** [comment]
@nishakm - try using `replace` statements like the following:
https://github.com/helm/helm/blob/0b2fec08ac2270a027fa3d9c216d269081c0b08d/go.mod#L51

**Comment by nishakm** [comment]
> @nishakm - try using `replace` statements like the following:
> https://github.com/helm/helm/blob/0b2fec08ac2270a027fa3d9c216d269081c0b08d/go.mod#L51

@jdolitsky Sorry for the late reply. It looks like the current go.mod file for oras does use the replace clause: https://github.com/deislabs/oras/blob/main/go.mod

However, if I run `go get` I get the above error.

**Comment by deitch** [comment]
I just ran into the same with 0.10.0.

I see the replacement clause, but anything that tries to include it blows up, error similar to what @nishakm has above. Something as simple as the following program:

```go
package main

import (
	"fmt"
	"github.com/deislabs/oras/pkg/content"
)

func main() {
	fmt.Println(content.DefaultBlobMediaType)
}
```

And then run `go run .` or `go vet .` and get:

```
go: finding module for package github.com/deislabs/oras/pkg/content
go: downloading github.com/deislabs/oras v0.10.0
go: found github.com/deislabs/oras/pkg/content in github.com/deislabs/oras v0.10.0
go: github.com/deislabs/oras@v0.10.0 requires
	github.com/docker/distribution@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by deitch** [comment]
This might be it. See [here](https://golang.org/cmd/go/#hdr-The_go_mod_file), the 6th paragraph:

```
Exclude and replace apply only in the main module's go.mod and are ignored in dependencies. See https://research.swtch.com/vgo-mvs for details.
```

Unfortunately, this seems to break using oras as a library.

**Comment by deitch** [comment]
Interestingly, a quick search shows github.com/docker/distribution is used only in docs and test files, while github.com/docker/docker (which the docker crew are highly discouraging people from using) is used in 3 places:

* https://github.com/deislabs/oras/blob/a64b0ac4faf26c58016fbd7ed1a9eb9d049e54ee/pkg/auth/docker/login.go
* https://github.com/deislabs/oras/blob/a64b0ac4faf26c58016fbd7ed1a9eb9d049e54ee/pkg/auth/docker/resolver.go
* https://github.com/deislabs/oras/blob/a64b0ac4faf26c58016fbd7ed1a9eb9d049e54ee/cmd/oras/login.go

All of which have been ported to moby/moby

Is there any reason we cannot just move those over and be done with it?

**Comment by jdolitsky** [comment]
@deitch - if you can make the transition and tests all pass, then please, yes.

FWIW - I've not found `go get` to be a reliable way to get Go packages in general. Especially since `go mod` stuff.

**Comment by deitch** [comment]
I just wasted too much time trying to get it to work. github.com/docker/distribution has been moved to github.com/distribution/distribution, but stuff in there still references docker/docker. it is a mess.

Just getting this to work as a library in a basic sense requires not using the illegal 01010000 pattern in `require`, because downstream dependency imports ignore the `replace` directive. Why? No idea.

Do you want to try and just use real import values?

**Comment by deitch** [comment]
See if this does it https://github.com/deislabs/oras/pull/218

**Comment by jdolitsky** [comment]
thanks. that is in main now. Can one of you let me know if that resolves it or if we need to make a new release?

**Comment by deitch** [comment]
It works for me. Can you check as well @nishakm ?

**Comment by nishakm** [comment]
@deitch n00b question: how do I make `go get` point to the tip of oras's main branch rather than `v0.10.0`?

**Comment by deitch** [comment]
`go get github.com/deislabs/oras@main` (or whatever the branch name is; you can use tags or a sha commit too)

**Comment by nishakm** [comment]
It works! Thanks!

**Comment by jdolitsky** [comment]
👍
