### ISSUE TITLE
default hybrid store on pull does not pass manifest and index through to ingester

### ISSUE THREAD

**Issue by deitch** [deislabs/oras#225]
Looking at this code [here](https://github.com/deislabs/oras/blob/a64b0ac4faf26c58016fbd7ed1a9eb9d049e54ee/pkg/oras/store.go#L56-L68):

```go
// Writer begins or resumes the active writer identified by desc
func (s *hybridStore) Writer(ctx context.Context, opts ...content.WriterOpt) (content.Writer, error) {
	var wOpts content.WriterOpts
	for _, opt := range opts {
		if err := opt(&wOpts); err != nil {
			return nil, err
		}
	}

	if isAllowedMediaType(wOpts.Desc.MediaType, ocispec.MediaTypeImageManifest, ocispec.MediaTypeImageIndex) || s.ingester == nil {
		return s.cache.Writer(ctx, opts...)
	}
	return s.ingester.Writer(ctx, opts...)
}
```

If the media type is a manifest or an index, it stores it in the cache - which can be a good thing, especially when the need to walk children comes about - but it doesn't pass it through to the ingester, as `s.cache` is just a `MemoryStore`.

Why would we want only to send the config and layers (and whatever other media types there are) through to the ingester? We don't know how it uses it, shouldn't it be up to the ingester to decide?

Strangely, I have had this work, so maybe I am missing something, or maybe it didn't work and I didn't fully realize it?

cc @jdolitsky @shizhMSFT

**Comment by deitch** [comment]
FWIW, if we can agree on this, I am happy to open a PR for this one and pass them through. I already solved it locally. Let me know.

**Comment by jdolitsky** [comment]
I would be fine with an an additional option such as `WithCachedMediaTypes` that allows you to supply your own, defaulting to `[]string{wOpts.Desc.MediaType, ocispec.MediaTypeImageManifest, ocispec.MediaTypeImageIndex}`

**Comment by deitch** [comment]
That could solve both. I will provide a PR for both the caching pass through and the mediatypes next week.
