### ISSUE TITLE
hybrid store caching misses docker media types but ChildrenHandler expects them

### ISSUE THREAD

**Issue by deitch** [deislabs/oras#226]
The caching code is [here](https://github.com/deislabs/oras/blob/a64b0ac4faf26c58016fbd7ed1a9eb9d049e54ee/pkg/oras/store.go#L64-L66):

```go
	if isAllowedMediaType(wOpts.Desc.MediaType, ocispec.MediaTypeImageManifest, ocispec.MediaTypeImageIndex) || s.ingester == nil {
		return s.cache.Writer(ctx, opts...)
	}
```

However, the containerd Children handler [here](https://github.com/containerd/containerd/blob/v1.4.3/images/image.go#L330-L369):

```go
	switch desc.MediaType {
	case MediaTypeDockerSchema2Manifest, ocispec.MediaTypeImageManifest:
		p, err := content.ReadBlob(ctx, provider, desc)
		if err != nil {
			return nil, err
		}

		// TODO(stevvooe): We just assume oci manifest, for now. There may be
		// subtle differences from the docker version.
		var manifest ocispec.Manifest
		if err := json.Unmarshal(p, &manifest); err != nil {
			return nil, err
		}

		descs = append(descs, manifest.Config)
		descs = append(descs, manifest.Layers...)
	case MediaTypeDockerSchema2ManifestList, ocispec.MediaTypeImageIndex:
		p, err := content.ReadBlob(ctx, provider, desc)
		if err != nil {
			return nil, err
		}

		var index ocispec.Index
		if err := json.Unmarshal(p, &index); err != nil {
			return nil, err
		}

		descs = append(descs, index.Manifests...)
	default:
		if IsLayerType(desc.MediaType) || IsKnownConfig(desc.MediaType) {
			// childless data types.
			return nil, nil
		}
		log.G(ctx).Debugf("encountered unknown type %v; children may not be fetched", desc.MediaType)
	}
```

expects the ability to read from the provider (in our case, the cache) for all _four_ media types (OCI manifest and index, docker manifest and manifest list). This means that if we actually do pull down some such from the docker types, it will try to read it, but it isn't cached, and will return a "not found" error.

The simplest solution appears to be to add the two media types - I have a PR about to submit for it - but I am concerned that the lack of passthrough (see #225) might mean this would break something else.

**Comment by shizhMSFT** [comment]
It is **by design** that `oras` works only with OCI manifests and index since `oras` stands for `OCI Registry As Storage`.

If you are interested in docker manifests for private uses, you may take a look at https://github.com/shizhMSFT/oras/tree/shizh/docker_manifest.

**Comment by deitch** [comment]
Actually, I agree with you, in principle. I far prefer to use OCI media types. But the real world is full of messy legacy things. It is entirely possible to have to deal with a registry that only supports legacy formats. ORAS mostly handles that ok, but every now and then runs into an issue, like here. 

- I'd love technical purity on this, but we should be able to handle it if it isn't that way. 

Why even have it in a supported media type if we will break?
