### ISSUE TITLE
v0.10.0 break downstreams for `go get`

### ISSUE THREAD

**Issue by morlay** [deislabs/oras#229]
When downstream dep `github.com/deislabs/oras` like `helm.sh/helm/v3`

if someone what to use `helm.sh/helm/v3`, go get will break (golang 1.16)
```
$  go get helm.sh/helm/v3@v3.5.2
go get: helm.sh/helm/v3@v3.5.1 updating to
        helm.sh/helm/v3@v3.5.2 requires
        github.com/deislabs/oras@v0.10.0 requires
        github.com/docker/distribution@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

We could use `replace` to fix this. 
but not all sub pkg dep `github.com/deislabs/oras`

**if the invalid version here, and all downstreams have to set the `replace`**

should avoid the invalid version  in go mod. like main branch did.

```
github.com/docker/distribution v0.0.0-00010101000000-000000000000
github.com/docker/docker v0.0.0-00010101000000-000000000000
```

only need to set replace, when real deps `github.com/deislabs/oras`
```
replace (
	github.com/docker/distribution => github.com/docker/distribution v0.0.0-20191216044856-a8371794149d
	github.com/docker/docker => github.com/moby/moby v17.12.0-ce-rc1.0.20200618181300-9dc6525e6118+incompatible
)
```

**Comment by deitch** [comment]
This is well known and fixed in #218. As soon as a new release is cut, it will automatically work downstream.

**Comment by morlay** [comment]
Cool. 

Waiting for next relaese 🎉

**Comment by deitch** [comment]
v0.11.0 is released, this should be fine now. Would you care to try it out @morlay and either comment if it is not, or close the issue?

**Comment by morlay** [comment]
@deitch works well. When PR merged, should be auto closed

**Comment by deitch** [comment]
It was merged a while ago, but we were waiting for the release. That was completed yesterday. Please close this out.
