### ISSUE TITLE
Failed to run the example with version 0.11.0

### ISSUE THREAD

**Issue by shizhMSFT** [deislabs/oras#246]
Here is the output of running `github.com/deislabs/oras/examples`:
```
Pushing hello.txt to localhost:5000/oras:test...
time="2021-03-17T23:50:21+08:00" level=warning msg="reference for unknown type: application/vnd.unknown.config.v1+json" digest="sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a" mediatype=application/vnd.unknown.config.v1+json size=2
time="2021-03-17T23:50:21+08:00" level=warning msg="reference for unknown type: my.custom.media.type" digest="sha256:03ba204e50d126e4674c005e04d82e84c21366780af1f43bd54a37816b6ab340" mediatype=my.custom.media.type size=13
Pushed to localhost:5000/oras:test with digest sha256:d3551d28503fc53dbb2f316bc71f3e0fd27772395c58ff32c35c9f137b70609a
Pulling from localhost:5000/oras:test and saving to hello.txt...
panic: no_name
```

It is a regression introduced by #230

**Comment by deitch** [comment]
That is pretty straightforward. Easy enough to fix.

I notice that the example depends on having a local registry at `localhost:5000` but doesn't say that anywhere.

**Comment by shizhMSFT** [comment]
@deitch Running a local registry is as easy as `docker run -itp 5000:5000 registry`.

**Comment by shizhMSFT** [comment]
I took a loot at #230, which fixes #225.

The idea of the `hybridStore` is that we don't care about the manifest and config in the regular `oras pull` scenarios, and they should not be presistent on the disk. That's why they are ingested in the memory as they ephemeral.

If a developer indeed want everything persist on the disk, the developer should pass the option `oras.WithContentProvideIngester()` to the `oras.Pull()` to override the `hybridStore`. In this case, `OCIStore` is suggested for storing everything. Ref: #108

**Comment by shizhMSFT** [comment]
I suggest to revert #230.

@jdolitsky @deitch Any thoughts?

**Comment by shizhMSFT** [comment]
I've submit a PR #249 for a hot fix since it is a critical bug that a manifest won't have a filename and thus pull always fail.

**Comment by deitch** [comment]
I commented there. Any kind of store should be able to handle any kind of content. If there are kinds of content that it cannot handle, then it has the choice of error or ignore, and that's a choice that should be made at the level of that store. Don't let it be a layer above. 

Now, if we want the default to be ignore, rather than error, as @jdolitsky suggested, let's do that.

**Comment by shizhMSFT** [comment]
> I commented there. Any kind of store should be able to handle any kind of content. If there are kinds of content that it cannot handle, then it has the choice of error or ignore, and that's a choice that should be made at the level of that store. Don't let it be a layer above.
> 
> Now, if we want the default to be ignore, rather than error, as @jdolitsky suggested, let's do that.

OK. I agree with this one. At least, we should try not to block user on default behaviors, especially for CLI users.

**Comment by jdolitsky** [comment]
PR to change the default behavior here: https://github.com/deislabs/oras/pull/250

This also adds an acceptance test to prevent this in the future
