### ISSUE TITLE
oras discover shouldn't require --artifact-type

### ISSUE THREAD

**Issue by SteveLasker** [deislabs/oras#252]
While the `artifact.manifest` references api may support filtering, not all registries may implement the filtering.
We also want to get a full collection of references, not limited by type

`oras discover --plain-http registry.wabbit-networks.io/net-monitor:v1` 

should also be valid

**Comment by shizhMSFT** [comment]
Note: this issue only applies to the `prototype-2` branch.

**Comment by shizhMSFT** [comment]
This work item depends on https://github.com/notaryproject/distribution/issues/4

**Comment by shizhMSFT** [comment]
Closed by 60b9dab763acec48c64b8d53c37f228ccc18d8cd
