### ISSUE TITLE
oras discover should return manifest collections

### ISSUE THREAD

**Issue by SteveLasker** [deislabs/oras#253]
Similar to the `/v2/_ext/oci-artifacts/v1/{repository}/manifests/{digest}/references?n=10&artifactType={artifactType}` response, we should return a list of manifests, and the digest. See [Artifact References API results](https://github.com/opencontainers/artifacts/pull/29/files#diff-f4344aacfe1e5014cc09cf55e7b548cb73a2b370cf3484ca81900b3ed54d44bcR44)

Output of `--output-json` should be consistent with the REST output

**Comment by shizhMSFT** [comment]
The raw API response from the distribution server should be transparent to the user.
The `oras` cli outputs the information in the same format of the API response but will never output the API response directly.

**Comment by shizhMSFT** [comment]
This work item depends on https://github.com/notaryproject/distribution/issues/4

**Comment by shizhMSFT** [comment]
Closed by db537ea3f63659f41738f5cfd24a7b47aab7959f
