### ISSUE TITLE
Require documentation

### ISSUE THREAD

**Issue by shizhMSFT** [deislabs/oras#59]
Write documentation under `/docs`

**Comment by shizhMSFT** [comment]
Major documentations can be found at [![GoDoc](https://godoc.org/github.com/deislabs/oras?status.svg)](https://godoc.org/github.com/deislabs/oras).

Requrie more docs on `configs` and `annotations`, some advanced usage of the file store.

**Comment by jdolitsky** [comment]
It would be nice also to have a lot of examples of common usages of the Go lib
