### ISSUE TITLE
Updating from commit 550ed34caf4a to 40d20966e9ea introduces ^M newline characters in code

### ISSUE THREAD

**Issue by bauerm97** [deislabs/oras#86]
Example:

```
diff --git a/vendor/github.com/deislabs/oras/pkg/oras/push_opts.go b/vendor/github.com/deislabs/oras/pkg/oras/push_opts.go
index b4d75daf5..fd60d666a 100644
--- a/vendor/github.com/deislabs/oras/pkg/oras/push_opts.go
+++ b/vendor/github.com/deislabs/oras/pkg/oras/push_opts.go
@@ -4,6 +4,7 @@ import (
        "path/filepath"
        "strings"
 
+       "github.com/containerd/containerd/images"^M
        orascontent "github.com/deislabs/oras/pkg/content"
 
        ocispec "github.com/opencontainers/image-spec/specs-go/v1"
@@ -15,6 +16,7 @@ type pushOpts struct {
        configAnnotations   map[string]string
        manifestAnnotations map[string]string
        validateName        func(desc ocispec.Descriptor) error
+       baseHandlers        []images.Handler^M
 }
 
 func pushOptsDefaults() *pushOpts {
@@ -98,3 +100,12 @@ func ValidateNameAsPath(desc ocispec.Descriptor) error {
 
        return nil
 }
+^M
+// WithPushBaseHandler provides base handlers, which will be called before^M
+// any push specific handlers.^M
+func WithPushBaseHandler(handlers ...images.Handler) PushOpt {^M
+       return func(o *pushOpts) error {^M
+               o.baseHandlers = append(o.baseHandlers, handlers...)^M
+               return nil^M
+       }^M
+}^M
```

This is just a subset of the diff, but these `^M` characters are scattered throughout

**Comment by bauerm97** [comment]
From what I can tell it appears to have been introduced (at least partially) in [this commit](https://github.com/deislabs/oras/commit/d1e019803abd85a80e26792d3ed827c0b2b5fc96)

**Comment by jdolitsky** [comment]
@bauerm97 yes, this something to do with Shiwei's machine :)

Is this affecting your importing of the code? Or is this just a general cosmetic thing?

**Comment by bauerm97** [comment]
@jdolitsky Just a general cosmetic thing. I have created a patch replacing all ^M characters in `.go` files. Let me know if you want a pull request submitted. The patch:

https://github.com/deislabs/oras/compare/master...bauerm97:fix-newline-char

**Comment by jdolitsky** [comment]
Awesome thanks. 
@shizhMSFT what do you think? Maybe we can add something to our `make test` that checks for this encoding issue so it doesnt continue happening, and another `make` target to fix it locally?

**Comment by jdolitsky** [comment]
@bauerm97 do you have a command you used to replace the chars?

**Comment by bauerm97** [comment]
@jdolitsky Yes, here's the command I used:

`$ find -type f -name "*.go" -exec sed -i s/^M//g {} +`

Note that in order to get the actual `^M` character you need to press `CTRL-V + M`. Just typing `^M` won't create the correct character. I did this from an ubuntu 18.04 terminal

**Comment by shizhMSFT** [comment]
@jdolitsky We can have a test on that. Many people like me are using Windows machines and they may not have a global setting on `core.autocrlf` as they may contribute to Windows-only projects.
