### ISSUE TITLE
Acceptance tests for compatibility against multiple registries

### ISSUE THREAD

**Issue by jdolitsky** [deislabs/oras#89]
Add acceptance test suite that ensures that ORAS CLI binary works against several registries:

- Local distribution server
- Azure ACR
- Quay.io (?)
- Amazon ECR (?)
- Google GCR (?)

Plan to use [Robot Framework](https://robotframework.org/)

**Comment by SteveLasker** [comment]
@jdolitsky, do we want to do this here, or make artifacts part of the OCI conformance tests?

**Comment by jdolitsky** [comment]
sure, will close for now
