### ISSUE TITLE
Pulling a single file from a repository

### ISSUE THREAD

**Issue by radu-matei** [deislabs/oras#91]
Supposing I pushed multiple files to a repository using `oras` - is it possible / reasonable to be able to pull only a single file (layer, in the current format), referenced by digest?

In the example below, to only pull the layer corresponding to the first file, `sha256:3fe24f297ab8bddcdef54e0fc016114e55e064d6a9e43834fd10963ba99d3cae`?

```
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 2
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:3fe24f297ab8bddcdef54e0fc016114e55e064d6a9e43834fd10963ba99d3cae",
      "size": 138,
      "annotations": {
        "org.opencontainers.image.title": "Makefile"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar",
      "digest": "sha256:040fc227a60a0de08a8083cee60bec935af2bebf81d665a3a8c0401988948a17",
      "size": 1082,
      "annotations": {
        "org.opencontainers.image.title": "LICENSE"
      }
    }
  ]
}
```

**Comment by jdolitsky** [comment]
@radu-matei yes, it is possible. We are still working on getting the docs together. Please take a look at the test method `Test_3_Conditional_Pull()` here: https://github.com/deislabs/oras/blob/master/pkg/oras/oras_test.go#L240

**Comment by radu-matei** [comment]
Nice, I'll have a look at that.
Thanks a lot, Josh!

Closing this.
