### ISSUE TITLE
Add Go examples section to docs

### ISSUE THREAD

**Issue by jdolitsky** [deislabs/oras#97]
The level of detail in the docs is great, but it would also be nice to have end-to-end examples of using the Go package for persons looking for a quick copy-paste (similar to whats at the bottom of README currently)

**Comment by garethr** [comment]
Agreed. [This](https://github.com/deislabs/oras/blob/master/examples/simple_push_pull.go) is great, but doesn't deal with authentication. Does a simple example with auth already exist? If not I think I need to create one and will post here.

**Comment by SteveLasker** [comment]
@jdolitsky I believe you have covered this in the current readme.md ?

**Comment by deitch** [comment]
Please, yes. I wasted too much time trying to figure out how the various parts work together. The simple readme.md doesn't handle auth, verbose/debug, etc.

**Comment by SteveLasker** [comment]
closing as we have some better docs, and [another issue for better logging](https://github.com/deislabs/oras/issues/140).
